/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WebServer */

#ifndef _Included_WebServer
#define _Included_WebServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WebServer
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_WebServer_init
  (JNIEnv *, jobject);

/*
 * Class:     WebServer
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_WebServer_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
